config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#toppage'
  resources :users
  resources :labels
  
  namespace :admin do
    resources :users
  end

  resources :sessions, only: %w!new create destroy!  
  resources :tasks 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
  belongs_to :user, optional: true
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  
  validates :title,  presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :priority, presence: true
  validates :deadline, presence: true
  validates :status, presence: true

  enum priority:{
    高: 0, 
    中: 1, 
    低: 2, 
  }

  # def self.search(search_params)
  #   Task.where(['title LIKE ?', "%#{search_params}%"])
  # end

  scope :sorted, -> { order(created_at: :desc) }
  #scope :recent, -> { active.sorted }
  scope :deadline_sort, -> { order(deadline: :desc) }
  scope :title_search, -> (search_params){ Task.where(['title LIKE ?', "%#{search_params}%"]) }
  scope :status_search, -> (search_params){ Task.where(['status LIKE ?', "%#{search_params}%"]) }
  scope :sort_priority, -> { order(priority: :asc) } 
  
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :last_user
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, on: :create
  validates :password, length: {minimum: 4}, on: :update, allow_blank: true

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
  
  def last_user
    count = User.count
    if count == 1
    throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :login?
  before_action :not_admin
  before_action :set_user, only: [:destroy, :edit, :update, :show]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
      redirect_to admin_users_path, notice: 'ユーザーを削除しました' 
  end

  def update
    @users = User.all
    if params[:admin_false] == 'true' && User.where(admin: true).count == 1
      redirect_to admin_users_path, notice: '管理ユーザが一人しかいないので消せません。'
    elsif @user.update(user_params)
      redirect_to admin_users_path, notice: 'ユーザー情報を更新しました'
    else
      render :edit 
    end
  end

  def edit
  end

  def show
    @tasks = Task.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザーを新規作成しました。'
    else
      render 'new'
    end
  end

  private

  def login?
    unless logged_in?
      redirect_to root_path, notice: 'ログインしてください'
    end
  end

  def not_admin
    redirect_to root_path, notice: 'No' unless current_user.try(:admin?)
  end 

  def set_user
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?

  protect_from_forgery with: :exception
  include SessionsHelper

  def production?
    Rails.env.production?
  end

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_NAME"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  before_action :not_label_create, only: [:new]

  def not_label_create
    unless logged_in?
      redirect_to root_path, notice: 'ログインしてください'
    end
  end

  def new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(label_params)
    if @label.save
      redirect_to user_path(current_user.id), notice: '登録完了'
    else
      render :new 
    end
  end

  def edit
  end

  def destroy
    @label.destroy
    redirect_to user_path(current_user.id), notice: '情報を削除しました' 
  end

  def show
    
  end

  private
  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :index, :new]

  def toppage
  end

  def authenticate_user
    unless logged_in?
      redirect_to root_path, notice: 'ログインしてください'
    end
  end

  def new
    @task = Task.new
  end

  def index
    @tasks = Task.all.sorted.page(params[:page]).per(5)
    if params[:sort_expired] == "true"
      @tasks = Task.all.deadline_sort.page(params[:page]).per(5)
    elsif params[:task].present?
      @tasks = Task.title_search(params[:task][:title_search]).page(params[:page]).per(5) 
      @tasks = @tasks.status_search(params[:task][:status_search]).page(params[:page]).per(5) if params[:task][:status_search].present?
      @tasks = @tasks.joins(:labels).where(labels: { id: params[:task][:label_id] }).page(params[:page]).per(5) if params[:task][:label_id].present?
    elsif params[:sort_priority] == "true"
      @tasks = Task.all.sort_priority.page(params[:page]).per(5)
    end
  end

  def show
    if current_user.id != @task.user_id
      redirect_to tasks_path, notice: 'あなたのタスクではありません。'
    end
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: '登録完了'
    else
      render :new 
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: '情報の編集が完了しました' 
    else
      render :edit
    end

  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: '情報を削除しました' 
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :deadline, :priority, :status, { label_ids: [] } )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_user_create, only: [:new]
  before_action :set_user, only:[:show, :edit, :update]
  
  def new
    @user = User.new
  end

  def not_user_create
    if logged_in?
      redirect_to tasks_path, notice: '新規登録する場合はログアウトしてください。'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @labels = Label.all
    if current_user.id != @user.id
      redirect_to tasks_path, notice: 'あなたのアカウントではありません。'
    end
  end

  def edit
    if current_user.id != @user.id
      redirect_to root_path, notice: 'あなたのアカウントではありません。'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報を更新しました' 
    else
      render :edit 
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

   # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true, url: admin_users_path ) do |form| %>
  <div class="errors">
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <ul class="field">
    <li><%= form.label t('view.name') %></li>
    <li><%= form.text_field :name %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.email') %></li>
    <li><%= form.text_field :email %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.password') %></li>
    <li><%= form.password_field :password %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.password_confirmation') %></li>
    <li><%= form.password_field :password_confirmation %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.admin') %></li>
    <li><%= form.select :admin, { true: "true", false: "false" } %></li>
  </ul>

  <ul class="actions">
    <li><%= form.submit %></li>
  </ul>
<% end %>
</div>

app/views/admin/users/edit.html.erb
<h1>ユーザー情報の編集</h1>

<%= form_with(model: @user, local: true, url: admin_user_path(@user)) do |form| %>
  <div class="errors">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <ul class="field">
    <li><%= form.label t('view.name') %></li>
    <li><%= form.text_field :name %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.email') %></li>
    <li><%= form.text_field :email %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.password') %></li>
    <li><%= form.password_field :password %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.password_confirmation') %></li>
    <li><%= form.password_field :password_confirmation %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.admin') %></li>
    <li><%= form.select :admin, { true: "true", false: "false" } %></li>
  </ul>

  <ul class="actions">
    <li><%= form.submit %></li>
  </ul>
<% end %>
</div>

<%= link_to '戻る', admin_users_path, class: "btn btn-info" %> 

app/views/admin/users/index.html.erb
<h1>管理者画面のユーザ一覧</h1>
<br>

<table>
  <thead>
    <tr>
      <th>admin</th>
      <th>Name</th>
      <th>Email</th>
      <th>タスク数</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.admin %></td>
        <td><%= user.id %>:<%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= link_to 'Show', admin_user_path(user.id) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if user.try(:admin?) %>
          <td><%= link_to '権限削除', admin_user_path(user, user: {admin: false}, admin_false: true), method: :patch,data: { confirm: '管理者権限を付与しますか?' } %></td>
        <% elsif %>
          <td><%= link_to '権限付与', admin_user_path(user, user: {admin: true}), method: :patch,data: { confirm: '管理者権限を削除しますか?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '新規ユーザ作成', new_admin_user_path, class: 'btn btn-success' %>

app/views/admin/users/new.html.erb
<h1><%= t('view.sign_up')%></h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', root_path, class: 'btn btn_default' %>

app/views/admin/users/show.html.erb
<h1>菅理画面：<%= @user.name %>さんのページ</h1>

<p>メールアドレス: <%= @user.email %></p>


<table>
  <thead>
    <tr>
      <th><%= t('view.title') %></th>
      <th><%= t('view.content') %></th>
      <th><%= t('view.deadline') %></th>
      <th><%= t('view.status') %></th>
      <th class='kado'><%= t('view.priority') %></th>
    
    </tr>
  </thead>

  <tbody>
    <% @tasks.where(user_id: @user.id).each do |task| %>
      <tr id='task_row'>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '設定変更', edit_admin_user_path(@user), class: 'btn btn-success' %> |
<%= link_to '戻る', :back, class: 'btn btn-warning' %> 

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true ) do |form| %>
  <div class="errors">
    <% if label.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

        <ul>
        <% label.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <ul class="field">
    <li><%= form.label t('view.name') %></li>
    <li><%= form.text_field :name %></li>
  </ul>

  <ul class="actions">
    <li><%= form.submit %></li>
  </ul>
<% end %>
</div>

app/views/labels/new.html.erb
<h1>rable new</h1>

<%= render 'form', label: @label %>
<%= link_to 'Back', :back, class: 'btn btn_default' %>

app/views/labels/show.html.erb
<strong>ラベル名</strong>
<h2><%= @label.name %></h2>

<%= link_to '消す', label_path, method: :delete, data: { confirm: '本当に消しますか？' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Bootstrap</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=/>万葉課題</a>
          </div>

          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% if logged_in? %>
                <li><%= link_to "#{current_user.name}さんのマイページ", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                <li><%= link_to "タスク一覧", tasks_path %></li>
                <li><%= link_to "xxx", root_path %></li>
              <% else %>
                <li><%= link_to "トップページ", root_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
                <li><%= link_to "新規登録", new_user_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="field">
    <li><%= form.label :title %></li>
    <li><%= form.text_field :title %></li>
  </ul>

  <ul class="field">
    <li><%= form.label :content %></li>
    <li><%= form.text_field :content %></li>
  </ul>

  <ul class="field">
    <li><%= form.label :deadline %></li>
    <li><%= form.date_select :deadline %></li>
  </ul>

  <ul class="field">
    <li><%= form.label :status %></li>
    <li><%= form.select :status, { 未着手: "未着手", 着手中: "着手中", 完了: "完了" } %>
  </ul>

   <ul class="field">
    <li><%= form.label :priority %></li>
    <li><%= form.select :priority, Task.priorities.keys %>
  </ul>

  <ul class="field">
  <li><%= form.collection_check_boxes :label_ids, Label.where('user_id = ? OR user_id IS NULL', current_user.id), :id, :name %></li>
  </ul>

  <ul class="actions">
    <li><%= form.submit %></li>
  </ul>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク情報の編集</h1>

<%= render 'form', task: @task %>
<%= link_to '戻る', @task, class: 'btn btn-success' %> 

app/views/tasks/index.html.erb
<h1>登録者一覧</h1>
<br>

<%= link_to "終了期限でソートする", tasks_path(sort_expired: true) %>
<br>
<%= link_to "優先順位でソートする", tasks_path(sort_priority: true) %>
<br>

<%= form_with(model: Task.new, method: :get, local: true, url: tasks_path) do |f| %>
<br>
  <%= f.label :label_id, "ラベル検索" %>
  <%= f.select :label_id, Label.pluck(:name, :id), { include_blank: true } %>
<br>

  <%= f.label :title_search, "タイトル検索" %>
  <%= f.text_field :title_search, class:'form-control'%>
  <%= f.hidden_field :search, value: 'true' %>

  <%= f.label :status_search, "ステータス検索" %>
  <%= f.select :status_search, { "": nil, 未着手: "未着手", 着手中: "着手中", 完了: "完了" } %>
  <%= f.hidden_field :status, value: 'true' %>
  <br>
  <%= f.submit '検索する', class: 'btn btn-info' %>
  <br><br><br>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= t('view.title') %></th>
      <th><%= t('view.content') %></th>
      <th><%= t('view.deadline') %></th>
      <th><%= t('view.status') %></th>
      <th class='kado'><%= t('view.priority') %></th>
      <th colspan="3"></th>
    
    </tr>
  </thead>

  <tbody>
    <% @tasks.where(user_id: current_user.id).each do |task| %>
      <tr id='task_row'>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td class="reset"><%= link_to 'Show', task %></td>
        <td class="reset reset-2"><%= link_to 'Edit', edit_task_path(task) %></td>
        <td class="reset reset-2"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% task.labels.each do |label| %>
            <p class='badge badge-primary'><%= label.name %></p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks.where(user_id: current_user.id) %>
<br>
<%= link_to 'New task', new_task_path, class: 'btn btn-info' %>

app/views/tasks/new.html.erb
<h1>新規タスク登録</h1>

<%= render 'form', task: @task %>
<%= link_to 'Back', root_path %>

app/views/tasks/show.html.erb
<h1>タスク</h1>

<p>
  <strong>タイトル:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>終了期限:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>ステータス:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>優先順位:</strong>
  <%= @task.priority %>
</p>

<p>
  <% if @task.labels.present? %>
    <strong>ラベル</strong>
    <% @task.labels.each do |label| %>
      <p class='badge badge-primary'><%= label.name %></p>
    <% end %>
  <% end %>
</p>

<%= link_to '設定変更', edit_task_path(@task), class: 'btn btn-success' %> |
<%= link_to '戻る', tasks_path, class: 'btn btn-warning' %> 

app/views/tasks/toppage.html.erb
<div class="toppage">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 toppage_center">
      <h2><%= link_to "ログイン", new_session_path, class: 'btn btn-info login_btn'%></h2>
      <br>
      <h4><%= link_to "初めての方はこちら", new_user_path %></h4>
    </div>
    <div class="col-md-2 toppage_right">
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true ) do |form| %>
  <div class="errors">
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <ul class="field">
    <li><%= form.label t('view.name') %></li>
    <li><%= form.text_field :name %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.email') %></li>
    <li><%= form.text_field :email %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.password') %></li>
    <li><%= form.password_field :password %></li>
  </ul>

  <ul class="field">
    <li><%= form.label t('view.password_confirmation') %></li>
    <li><%= form.password_field :password_confirmation %></li>
  </ul>

  <ul class="actions">
    <li><%= form.submit %></li>
  </ul>
<% end %>
</div>

app/views/users/edit.html.erb
<h1><%= t('view.edit')%>画面</h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', user_path(@user), class: 'btn btn_default' %>

app/views/users/new.html.erb
<h1><%= t('view.sign_up')%></h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', root_path, class: 'btn btn_default' %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>タスク数: <%= @user.tasks.count %></p>

<p>あなたのオリジナルラベル</p>
<% @labels.where(user_id: current_user.id).each do |label| %>
  <p class='badge badge-primary user_show_link'><%= link_to label.name, label_path(label) %></p>
<% end %>
<br>


<%= link_to 'オリジナルラベルを作成する', new_label_path, class: 'btn btn-info' %>
<br><br>

<%= link_to '設定変更', edit_user_path(@user), class: 'btn btn-success' %> |
<%= link_to '戻る', :back, class: 'btn btn-warning' %> 